HEADER_MAP = {
    "hourly_rate": "hourly_rate",
    "rate": "hourly_rate",
    "salary": "hourly_rate",
    "pay_rate": "hourly_rate",
    "wage": "hourly_rate",
    "hour_rate": "hourly_rate",
    "RATE": "hourly_rate",
    "SALARY": "hourly_rate",
    "PAY_RATE": "hourly_rate",
    "WAGE": "hourly_rate",
    "HOUR_RATE": "hourly_rate",

    "hours_worked": "hours_worked",
    "hours": "hours_worked",
    "worked_hours": "hours_worked",
    "work_hours": "hours_worked",
    "time": "hours_worked",
    "HOURS_WORKED": "hours_worked",
    "WORKED_HOURS": "hours_worked",
    "TIME": "hours_worked",

    "department": "department",
    "dept": "department",
    "division": "department",
    "team": "department",
    "DEPARTMENT": "department",
    "DEPT": "department",
    "DIVISION": "department",
    "TEAM": "department",

    "name": "name",
    "full_name": "name",
    "employee_name": "name",
    "staff_name": "name",
    "NAME": "name",
    "FULL_NAME": "name",
    "EMPLOYEE_NAME": "name",
    "STAFF_NAME": "name",
}
